site_name: defi-aeas
site_url: ''
site_description: Exploring DeFi AEAs
repo_url: https://github.com/DavidMinarsch/defi-aeas
site_author: developer@fetch.ai

theme:
  name: material
  logo:
    icon: code
  feature:
    tabs: false

strict: true

nav:
  - Introduction: index.md
  - Architecture:
      - Overview: overview.md
      - Pool APR Skill: pool_apr.md
      - Capital Allocation Skill: capital_allocation.md
      - App-Agent Flow: app-agent-interactions.md

plugins:
    - markdownmermaid
    - search

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - admonition

extra_javascript:
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js